/* =============================================================================
   Shell | Fabric SQL Database | 03 - Value mapping (reference for cleaning)
   One table maps every messy spelling found in the raw files to its clean value.
   Lookups use TRIM(raw) and the database's case-insensitive collation, so
   'UNITED KINGDOM ', 'united kingdom' and 'United Kingdom' all hit one row.
   New spellings found later go to etl.rejected_rows and are added here.
============================================================================= */
DROP TABLE IF EXISTS etl.value_map;
CREATE TABLE etl.value_map (
    domain       NVARCHAR(30)  NOT NULL,   -- country | product | cause | contract_type | scope | flag
    raw_value    NVARCHAR(100) NOT NULL,
    clean_value  NVARCHAR(100) NOT NULL,
    CONSTRAINT pk_value_map PRIMARY KEY (domain, raw_value)
);

INSERT INTO etl.value_map (domain, raw_value, clean_value) VALUES
 ('cause', N'3rd party', N'Third party'),
 ('cause', N'PLANNED MAINTENANCE', N'Planned maintenance'),
 ('cause', N'Planned Maint.', N'Planned maintenance'),
 ('cause', N'THIRD PARTY', N'Third party'),
 ('cause', N'UNPLANNED', N'Unplanned'),
 ('cause', N'WEATHER', N'Weather'),
 ('cause', N'Weather/Storm', N'Weather'),
 ('contract_type', N'LONG TERM', N'Long-term'),
 ('contract_type', N'LT', N'Long-term'),
 ('contract_type', N'Long-term', N'Long-term'),
 ('contract_type', N'SPOT', N'Spot'),
 ('contract_type', N'Spot cargo', N'Spot'),
 ('country', N'AU', N'AU'),
 ('country', N'AUS', N'AU'),
 ('country', N'Australia', N'AU'),
 ('country', N'BR', N'BR'),
 ('country', N'Brasil', N'BR'),
 ('country', N'Brazil', N'BR'),
 ('country', N'CA', N'CA'),
 ('country', N'CAN', N'CA'),
 ('country', N'CH', N'CH'),
 ('country', N'CHN', N'CN'),
 ('country', N'CN', N'CN'),
 ('country', N'Canada', N'CA'),
 ('country', N'China', N'CN'),
 ('country', N'DE', N'DE'),
 ('country', N'Deutschland', N'DE'),
 ('country', N'EG', N'EG'),
 ('country', N'EGY', N'EG'),
 ('country', N'ES', N'ES'),
 ('country', N'Egypt', N'EG'),
 ('country', N'España', N'ES'),
 ('country', N'GB', N'GB'),
 ('country', N'Germany', N'DE'),
 ('country', N'Great Britain', N'GB'),
 ('country', N'Holland', N'NL'),
 ('country', N'IN', N'IN'),
 ('country', N'IND', N'IN'),
 ('country', N'India', N'IN'),
 ('country', N'JP', N'JP'),
 ('country', N'JPN', N'JP'),
 ('country', N'Japan', N'JP'),
 ('country', N'KAZ', N'KZ'),
 ('country', N'KOR', N'KR'),
 ('country', N'KR', N'KR'),
 ('country', N'KZ', N'KZ'),
 ('country', N'Kazakhstan', N'KZ'),
 ('country', N'Korea', N'KR'),
 ('country', N'MX', N'MX'),
 ('country', N'MY', N'MY'),
 ('country', N'MYS', N'MY'),
 ('country', N'Malaysia', N'MY'),
 ('country', N'Mexico', N'MX'),
 ('country', N'México', N'MX'),
 ('country', N'NETHERLANDS', N'NL'),
 ('country', N'NG', N'NG'),
 ('country', N'NGA', N'NG'),
 ('country', N'NL', N'NL'),
 ('country', N'Nigeria', N'NG'),
 ('country', N'OM', N'OM'),
 ('country', N'Oman', N'OM'),
 ('country', N'PL', N'PL'),
 ('country', N'POLAND', N'PL'),
 ('country', N'PRC', N'CN'),
 ('country', N'Polska', N'PL'),
 ('country', N'QA', N'QA'),
 ('country', N'QAT', N'QA'),
 ('country', N'Qatar', N'QA'),
 ('country', N'Republic of Korea', N'KR'),
 ('country', N'SG', N'SG'),
 ('country', N'SGP', N'SG'),
 ('country', N'Schweiz', N'CH'),
 ('country', N'Singapore', N'SG'),
 ('country', N'South Korea', N'KR'),
 ('country', N'Spain', N'ES'),
 ('country', N'Sultanate of Oman', N'OM'),
 ('country', N'Switzerland', N'CH'),
 ('country', N'U.K.', N'GB'),
 ('country', N'U.S.A.', N'US'),
 ('country', N'UK', N'GB'),
 ('country', N'US', N'US'),
 ('country', N'USA', N'US'),
 ('country', N'United Kingdom', N'GB'),
 ('country', N'United States', N'US'),
 ('country', N'United States of America', N'US'),
 ('country', N'the Netherlands', N'NL'),
 ('flag', N'0', N'0'),
 ('flag', N'1', N'1'),
 ('flag', N'FALSE', N'0'),
 ('flag', N'N', N'0'),
 ('flag', N'TRUE', N'1'),
 ('flag', N'Y', N'1'),
 ('flag', N'no', N'0'),
 ('flag', N'yes', N'1'),
 ('product', N'Autogas', N'P04'),
 ('product', N'CAR WASH', N'P06'),
 ('product', N'Carwash', N'P06'),
 ('product', N'Convenience Shop', N'P05'),
 ('product', N'DIESEL', N'P02'),
 ('product', N'Gasoil', N'P02'),
 ('product', N'LPG', N'P04'),
 ('product', N'P01', N'P01'),
 ('product', N'P02', N'P02'),
 ('product', N'P03', N'P03'),
 ('product', N'P04', N'P04'),
 ('product', N'P05', N'P05'),
 ('product', N'P06', N'P06'),
 ('product', N'SHOP', N'P05'),
 ('product', N'UNLEADED 95', N'P01'),
 ('product', N'Unl 95', N'P01'),
 ('product', N'Unleaded95', N'P01'),
 ('product', N'V Power', N'P03'),
 ('product', N'V-POWER', N'P03'),
 ('product', N'VPower', N'P03'),
 ('scope', N'1', N'1'),
 ('scope', N'2', N'2'),
 ('scope', N'3', N'3'),
 ('scope', N'SCOPE 1', N'1'),
 ('scope', N'SCOPE 2', N'2'),
 ('scope', N'SCOPE 3', N'3'),
 ('scope', N'Scope1', N'1'),
 ('scope', N'Scope2', N'2'),
 ('scope', N'Scope3', N'3');

SELECT domain, COUNT(*) AS spellings, COUNT(DISTINCT clean_value) AS clean_values
FROM etl.value_map GROUP BY domain ORDER BY domain;
